const IMAGES = {
    DIAMOND_BLOCK: "graphics/blocks/diamondBlock.png",
    DIAMOND_BLOCK2: "graphics/blocks/diamondBlock2.png",
    ICE_BLOCK: "graphics/blocks/iceBlock.png",
    ICE_BLOCK2: "graphics/blocks/iceBlock2.png",
    ORANGE_BLOCK: "graphics/blocks/orangeBlock.png",
    PENGO_LEFT1: "graphics/pengo/left/1.png",
    PENGO_LEFT2: "graphics/pengo/left/2.png",
    PENGO_RIGHT1: "graphics/pengo/right/1.png",
    PENGO_RIGHT2: "graphics/pengo/right/2.png",
    PENGO_UP1: "graphics/pengo/up/1.png",
    PENGO_UP2: "graphics/pengo/up/2.png",
    PENGO_DOWN1: "graphics/pengo/down/1.png",
    PENGO_DOWN2: "graphics/pengo/down/2.png",
    PENGO_DEAD1: "graphics/pengo/dead/1.png",
    PENGO_DEAD2: "graphics/pengo/dead/2.png",
    PENGO_PUSH_LEFT: "graphics/pengo/pushLeft.png",
    PENGO_PUSH_RIGHT: "graphics/pengo/pushRight.png",
    PENGO_PUSH_UP: "graphics/pengo/pushUp.png",
    PENGO_PUSH_DOWN: "graphics/pengo/pushDown.png",
    OBSTACLE_DESTROY1: "graphics/blocks/destroyAnimation/1.png",
    OBSTACLE_DESTROY2: "graphics/blocks/destroyAnimation/2.png",
    OBSTACLE_DESTROY3: "graphics/blocks/destroyAnimation/3.png",
    OBSTACLE_DESTROY4: "graphics/blocks/destroyAnimation/4.png",
    OBSTACLE_DESTROY5: "graphics/blocks/destroyAnimation/5.png",
    OBSTACLE_DESTROY6: "graphics/blocks/destroyAnimation/6.png",
    OBSTACLE_DESTROY7: "graphics/blocks/destroyAnimation/7.png",
    OBSTACLE_DESTROY8: "graphics/blocks/destroyAnimation/8.png",
    OBSTACLE_DESTROY9: "graphics/blocks/destroyAnimation/9.png",
    OPPONENT_LEFT1: "graphics/opponent/left/1.png",
    OPPONENT_LEFT2: "graphics/opponent/left/2.png",
    OPPONENT_RIGHT1: "graphics/opponent/right/1.png",
    OPPONENT_RIGHT2: "graphics/opponent/right/2.png",
    OPPONENT_UP1: "graphics/opponent/up/1.png",
    OPPONENT_UP2: "graphics/opponent/up/2.png",
    OPPONENT_DOWN1: "graphics/opponent/down/1.png",
    OPPONENT_DOWN2: "graphics/opponent/down/2.png",
    OPPONENT_SMASHED_LEFT: "graphics/opponent/smashedLeft.png",
    OPPONENT_SMASHED_RIGHT: "graphics/opponent/smashedRight.png",
    OPPONENT_SMASHED_UP: "graphics/opponent/smashedUp.png",
    OPPONENT_SMASHED_DOWN: "graphics/opponent/smashedDown.png",
};

const SOUNDS = {
    LEVEL_START: new Audio("sounds/act-start.mp3"),
    PUSH_ICE_BLOCK: new Audio("sounds/push-ice-block.mp3"),
    ICE_BLOCK_DESTROYED: new Audio("sounds/ice-block-destroyed.mp3"),
    OPPONENT_SPAWNING: new Audio("sounds/snow-bee-spawning.mp3"),
    PLAYER_KILLED: new Audio("sounds/miss.mp3"),
    OPPONENT_KILLED: new Audio("sounds/snow-bee-squashed.mp3"),
    BACKGROUND_MUSIC: new Audio("sounds/main-bgm-popcorn-.mp3"),
}